//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BussinessSite.DataLayerMSSql
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserEntity
    {
        public int id { get; set; }
        public string UName { get; set; }
        public string ULogin { get; set; }
        public Nullable<int> activ { get; set; }
        public string Pass { get; set; }
        public string Desc { get; set; }
    }
}
